server:
  port: 8998
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          username: cjianxun@126.com
          uri: https://github.com/fendou20190323/config.git
          password: cuijianxun0323
          default-label: master
