server:
  port: 9901
spring:
  application:
    name: update-bug
  datasource:
#    username:  root
#    password: lssMysql2@
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://rm-2ze877ndr3zv6a7z3.mysql.rds.aliyuncs.com:3306/scb?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
#      生产
#    username: xqyydbuser
#    password: yyDb123456
      #    url: jdbc:mysql://rm-2ze877ndr3zv6a7z3vo.mysql.rds.aliyuncs.com:3306/imis?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useAffectedRows=true
#      虚拟机
#    username: root
#    password: 123456
#    url: jdbc:mysql://192.168.218.128:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useAffectedRows=true
#      预生产
#    username: root
#    password: lssMysql2@
#    url: jdbc:mysql://39.106.48.118:3306/imis?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useAffectedRows=true
#     测试
    username: root
    password: root123456
    url: jdbc:mysql://11.1.1.143:33066/retailstore?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useAffectedRows=true
  main:
    allow-bean-definition-overriding: true
logging.level.com.fendou.moudle: debug
mybatis:
  mapper-locations: classpath:mapping/*.xml
  configuration:
    cache-enabled: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
#spring.datasource.username=root
#spring.datasource.password=root123456
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.datasource.url=jdbc:mysql://11.1.1.143:33066/scb?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useAffectedRows=true
