server:
  port: 9904
logging.level.com.fendou.moudle: debug
spring:
  application:
    name: es_service
  data:
    elasticsearch:
      cluster-name: my_es
      cluster-nodes: 192.168.218.128:9300,192.168.218.128:9301