server:
  port: 9903

logging.level.com.fendou.moudle: debug
  spring.rabbitmq.host=11.1.1.143
  spring.rabbitmq.port=5672
#spring.rabbitmq.username
#spring.rabbitmq.password
#spring.datasource.username=root
#spring.datasource.password=root123456
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.datasource.url=jdbc:mysql://11.1.1.143:33066/scb?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useAffectedRows=true
spring:
  rabbitmq:
    host: 192.168.218.128
    port: 5672
    username: admin
    password: admin
    publisher-confirms: true  #发送确认
    publisher-returns: true   #发送失败返回
#    listener:
#      simple:
#          acknowledge-mode: none
#          acknowledge-mode: auto
#          acknowledge-mode: manual
  #        retry:
#          enabled: false   #开启消费者重试
#          max-attempts: 5          #最大重试次数（重试5次还不行则会把消息删掉，默认是不限次数的，次数建议控制在10次以内）
#          initial-interval: 1000   #重试间隔时间
  application:
    name: mq_service2
