server:
  port: 10002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8999/eureka/
  instance:
    instance-id: redis_service:10002
spring:
  application:
    name: redis_service

  redis:
    host: 192.168.218.128
    port: 6379
